name: Link Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check links
        uses: lycheeorg/lychee-action@v2
        with:
          args: --verbose --no-progress './README.md'
          fail: true
